# Site
repository: Baune8D/baune8d.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Morten Baunegaard Larsen
title: Softwareudvikler
email: baunegaard@live.dk
# website: Your website (eg. https://google.com)(optional)

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: Baunegaard
github_username: Baune8D
# stackoverflow_username: "4418406"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: morten-larsen-47742bb4
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
#  - title: Link name
#    icon: Font Awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#    url: Link url (eg. https://google.com)
#  - title: another link
#    icon: font awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#    url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Om mig
about_profile_image: images/Morten.png
about_content: |
  Mit navn er Morten Larsen, og jeg er full stack web udvikler. Jeg startede da jeg var 14 år gammel med at programmere små konsol programmer i C++. Jeg har hele mit liv været interessert i IT og elektronik, og har i dag gjort programmering til min levevej.

  Jeg er en strategisk tænker, og har via mit engagement og partnerskab i Saxis.dk haft det ultimative ansvar for den samlede IT infrastruktur, udviklere, programmering og beslutningstagning.
  
  Som programmør er jeg meget perfektionistisk, jeg elsker at skrive god og velorganiseret kode, og lægger altid mange tanker i designet bag en opgave. Min primære interesse er backend udvikling, og jeg er specielt glad for Domain Driven Design. Jeg er ekstrem alsidig, og har erfaring indenfor alle områder af IT, hvorved jeg kan arbejde med det meste. Jeg har i min karriere bl.a. stået for opsætning og vedligeholdelse af både Windows og Linux servere, samt opsætning af flere CI/CD systemer.

  Det jeg værdsætter højt i et job er et godt arbejdsmiljø, og gode muligheder for at udvikle mig professionelt. Jeg søger altid at blive bedre til det jeg laver, og jeg elsker at udforske nye områder.

  I forhold til programmeringssprog er mit primære fokus på <mark>C#</mark> (.NET) og <mark>TypeScript</mark>, men jeg har også en stor interresse i DevOps og infrastruktur.

content:
  - title: Projekter
    layout: list
    content:
      - layout: top-middle
        title: LinqBuilder
        link: https://github.com/Baune8D/LinqBuilder
        additional_links:
          - title: Baune8D/LinqBuilder
            icon: fab fa-github
            url: https://github.com/Baune8D/LinqBuilder
        quote: >
          LinqBuilder is an advanced implementation of the specification pattern specifically targeting LINQ query generation.
        description: |
          [![Build status](https://ci.appveyor.com/api/projects/status/v0t8rfsv0d4q3hap?svg=true)](https://ci.appveyor.com/project/Baune8D/linqbuilder)
          [![codecov](https://codecov.io/gh/Baune8D/linqbuilder/branch/main/graph/badge.svg)](https://codecov.io/gh/Baune8D/linqbuilder)
          [![NuGet Badge](https://buildstats.info/nuget/LinqBuilder)](https://www.nuget.org/packages/LinqBuilder)
      - layout: top-middle
        title: ExpressionCache
        link: https://github.com/Baune8D/ExpressionCache
        additional_links:
          - title: Baune8D/ExpressionCache
            icon: fab fa-github
            url: https://github.com/Baune8D/ExpressionCache
        quote: >
          ExpressionCache takes advantage of expressions to generate and maintain cache keys for your application.
        description: |
          [![Build status](https://ci.appveyor.com/api/projects/status/0abskdimkpe1m558?svg=true)](https://ci.appveyor.com/project/Baune8D/expressioncache)
          [![codecov](https://codecov.io/gh/Baune8D/expressioncache/branch/main/graph/badge.svg)](https://codecov.io/gh/Baune8D/expressioncache)
          [![NuGet Badge](https://buildstats.info/nuget/ExpressionCache.Core)](https://www.nuget.org/packages/ExpressionCache.Core)
      - layout: top-middle
        title: AspNetWebpack
        link: https://github.com/Baune8D/AspNetWebpack
        additional_links:
          - title: AspNetWebpack
            icon: fab fa-github
            url: https://github.com/Baune8D/AspNetWebpack
        quote: >
          Template and tools for using Webpack with any type of ASP.NET Core project.
        description: |
          Dette projektet viser en template for at integrere Webpack, ESLint, StyleLint og Prettier, med et ASP.NET Core projekt. Projektet inkluderer værktøjer som gør det så nemt som muligt at bundle frontend kode sammen, og bruge det i både MVC views og Razor pages. Derudover kan konfigurationerne nemt udvides, hvilket giver mulighed for integration af fx. TypeScript eller et SPA framework.

  - title: Erfaring
    layout: list
    content:
      - layout: left
        title: Visma Dinero ApS
        link: https://www.dinero.dk
        sub_title: Softwareudvikler
        caption: 2021 - nu
        quote: >
           Danmarks bedste online regnskabsprogram
        description: |
          I mit job hos Dinero er jeg til daglig primært tilknyttet platform og infrastruktur teamet, men jeg har også lavet feature udvikling på både backend og frontend.

          Mit arbejde har bl.a. bestået af:
          * Udvikling af interne værktøjer til opsætning af det lokale udviklingsmiljø.
          * Migrering af legacy kodebaser til nyeste .NET versioner.
          * Vedligholdelse og optimering af CI/CD systemer.
          * Optimering af frontend build systemer.
          * Backend feature udvikling i .NET.
          * Frontend feature udvikling i TypeScript / AngularJS.

          Nogle public projekter jeg har stået for:
          * [willy-cli](https://www.npmjs.com/package/willy-cli) - Lokalt CLI værktøj til opsætning og vedligeholdelse af det lokale udviklings miljø.
          * [datadog-core](https://www.npmjs.com/package/@dineroregnskab/datadog-core) / [datadog-browser](https://www.npmjs.com/package/@dineroregnskab/datadog-browser) / [datadog-angular](https://www.npmjs.com/package/@dineroregnskab/datadog-angular) - Pakker til integration af Datadog i diverse frontends.
          * [node-logging](https://www.npmjs.com/package/@dineroregnskab/node-logging) / [espress-logging](https://www.npmjs.com/package/@dineroregnskab/express-logging) / [micro-logging](https://www.npmjs.com/package/@dineroregnskab/micro-logging) - Pakker til opsætning af request logging i diverse JS backend frameworks til Elasticsearch.

          Sprog: <mark>C#</mark> <mark>JavaScript</mark> <mark>TypeScript</mark> <mark>PowerShell</mark>  
          Frameworks: <mark>.NET</mark> <mark>AngularJS</mark>  
          Databaser: <mark>PostgreSQL</mark> <mark>MSSQL</mark>  
          Værktøjer: <mark>RabbitMQ</mark> <mark>Docker</mark> <mark>TeamCity</mark>  
          Arkitektur: <mark>DDD</mark> <mark>Microservices</mark> <mark>ASP.NET MVC</mark> <mark>ASP.NET Core MVC</mark>  
          Pakker: <mark>MassTransit</mark> <mark>Entity Framework</mark> <mark>Marten</mark> <mark>Autofac</mark> <mark>Hangfire</mark>
      - layout: left
        title: Capino (Saxis ApS)
        link: https://www.capino.dk
        sub_title: CTO & Co-Founder
        caption: 2020 - 2021
        quote: >
          Find kapital, lån eller en investor til dit firma eller projekt
        description: |
          Saxis overtog kodebasen i et meget tidligt stadie. Første version blev udgivet i 2020.

          Jeg er stadig tilknyttet Capino idag på konsulent basis.

          Mit arbejde har bl.a. bestået af:
          * Opsætning af servere til drift af sitet.
          * Opsætning af CI/CD pipline via Envoyer.io
          * Backend feature udvikling i PHP Laravel
          * Frontend feature udvikling i JavaScript / Vue.js

          Sprog: <mark>PHP</mark> <mark>JavaScript</mark> <mark>SASS</mark>  
          Frameworks: <mark>Laravel</mark> <mark>Vue.js</mark>  
          Databaser: <mark>MySQL</mark>  
          Værktøjer: <mark>Envoyer.io</mark> <mark>Wordpress</mark>  
          Infrastruktur: <mark>Ubuntu Server</mark> <mark>Apache</mark> <mark>VMware</mark>
      - layout: left
        title: Saxis ApS
        link: https://www.saxis.dk
        sub_title: CTO & Co-Founder
        caption: 2016 - 2021
        quote: >
          Stedet hvor sælgere og købere af små og mellemstore virksomheder mødes
        description: |
          Dette projekt var originalt en underside til Amino, kaldet "Amino Virksomhedsbørs" og skrevet i ASP.NET MVC på .NET Framework. Projektet blev originalt startet i 2007 af bl.a. Martin Thorborg. I 2016 købte jeg og 2 andre 50% af Amino Virksomhedsbørs og startede Saxis, projektet blev separeret fra Amino og flyttet til sit eget domæne: [www.saxis.dk](https://www.saxis.dk). I dag er der intet tilbage af den originale kodebase, jeg har igennem årene omskrevet hele sitet til en moderne kodebase skrevet primært i ASP.NET Core, og med vægt på SOLID principperne og DDD.
          
          Virksomheden vandt en Børsen Gazelle i 2020.
          
          Jeg er fortsat medejer og tilknyttet Saxis som jeg har brugt de sidste mange år på at bygge.

          Mit arbejde har bl.a. bestået af:
          * Omskrivning af website fra .NET Framework til .NET Core
          * Omskrivning af data access lag fra plain SQL til Code-First Entity Framework
          * Backend feature udvikling i .NET
          * Frontend feature udvikling i JavaScript / TypeScript / Vue.js

          Sprog: <mark>C#</mark> <mark>JavaScript</mark> <mark>TypeScript</mark> <mark>CSS</mark> <mark>SASS</mark> <mark>PowerShell</mark>  
          Frameworks: <mark>.NET</mark> <mark>Vue.js</mark>  
          Databaser: <mark>MSSQL</mark> <mark>MySQL</mark>  
          Værktøjer: <mark>Docker</mark> <mark>Webpack</mark> <mark>Redis</mark> <mark>Wordpress</mark>  
          Infrastruktur: <mark>Windows Server</mark> <mark>IIS</mark> <mark>Ubuntu Server</mark> <mark>Apache</mark> <mark>AppVeyor</mark> <mark>GitHub Actions</mark> <mark>VMware</mark>  
          Arkitektur: <mark>ASP.NET Core MVC</mark> <mark>Razor Pages</mark>  
          Pakker: <mark>Entity Framework</mark> <mark>Dapper</mark> <mark>AutoMapper</mark> <mark>MediatR</mark> <mark>Hangfire</mark> <mark>Autofac</mark> <mark>CacheManager</mark>
      - layout: left
        title: Min-Mave ApS
        link: https://www.min-mave.dk
        sub_title: Softwareudvikler
        caption: 2014 - 2016
        quote: >
          Danmarks største site for gravide og småbørnsforældre
        description: |
          Under mit arbejde for Amino havde jeg også en stor del af ansvaret for Min-Mave, som på det tidspunkt var tæt knyttet med Amino. Som den primære udvikler, stod jeg for det meste af programmeringsarbejdet i samarbejde med et Filippinsk udviklingshold.

          Reference kan sendes på anmodning.

          Mit arbejde har bl.a. bestået af:
          * Migrering af kodebase fra Mercurial til GIT.
          * Flyt af servere fra bare-metal til virtualiseret ESXi miljø.
          * Opsætning af CI/CD pipeline via TeamCity og Octopus Deploy.
          * Backend feature udvikling i .NET.
          * Frontend feature udvikling i JavaScript / jQuery.

          Sprog: <mark>C#</mark> <mark>JavaScript</mark> <mark>CSS</mark>  
          Frameworks: <mark>.NET</mark>  
          Databaser: <mark>MSSQL</mark> <mark>MySQL</mark>  
          Værktøjer: <mark>TeamCity</mark> <mark>Octopus Deploy</mark> <mark>Wordpress</mark>  
          Infrastruktur: <mark>Windows Server</mark> <mark>IIS</mark> <mark>Ubuntu Server</mark> <mark>Apache</mark> <mark>VMware</mark>  
          Arkitektur: <mark>ASP.NET MVC</mark>
      - layout: left
        title: Amino ApS
        link: https://www.amino.dk
        sub_title: Softwareudvikler
        caption: 2014 - 2016
        quote: >
          Mødestedet for mere end 100.000 iværksættere og selvstændige erhvervsdrivende.
        description: |
          Inden jeg stoppede som fuldtid på sitet i 2016 for at arbejde med Saxis, var jeg chefudvikler på projektet med det overordnede ansvar for alle udviklingsopgaver, samt drift og vedligeholdelse af servere og infrastruktur. Platformen var primært skrevet i C# i en blanding af MVC og Web Forms, samt nogle mindre projekter skrevet i PHP, så jeg har arbejdet både med nyudvikling, samt vedligeholdelse af legacy kodebaser. Udover programmering har jeg bl.a. også stået for migrering af kodebasen fra SVN til GIT, samt migrering af bare-metal servere til et ESXi virtualiseret setup. Jeg har også moderniseret arbejdsgangen ved opsætning af en fuld CI/CD pipeline bestående af TeamCity og Octopus Deploy.

          Reference kan sendes på anmodning.

          Mit arbejde har bl.a. bestået af:
          * Migrering af kodebase fra SVN til GIT.
          * Flyt af servere fra bare-metal til virtualiseret ESXi miljø.
          * Opsætning af CI/CD pipeline via TeamCity og Octopus Deploy.
          * Backend feature udvikling i .NET.
          * Frontend feature udvikling i JavaScript / jQuery.

          Sprog: <mark>C#</mark> <mark>JavaScript</mark> <mark>CSS</mark>  
          Frameworks: <mark>.NET</mark>  
          Databaser: <mark>MSSQL</mark> <mark>MySQL</mark>  
          Værktøjer: <mark>TeamCity</mark> <mark>Octopus Deploy</mark> <mark>Wordpress</mark>  
          Infrastruktur: <mark>Windows Server</mark> <mark>IIS</mark> <mark>Ubuntu Server</mark> <mark>Apache</mark> <mark>VMware</mark>  
          Arkitektur: <mark>ASP.NET MVC</mark> <mark>ASP.NET Web Forms</mark>
      - layout: left
        title: Hi-Fi Klubben A/S
        link: https://www.hifiklubben.dk
        sub_title: Salgsmedarbejder
        caption: 2011 - 2021
        quote: >
          I HiFi Klubben handler alting om lyd og billede - ikke køleskabe, vaskemaskiner og stavblendere. Hos os får du musik- og filmoplevelser for hver eneste krone
        description: |
          Jeg startede som deltid i Hi-Fi Klubben under mit studie som Datamatiker, men min store passion for elektronik holdte mig tilknyttet til Hi-Fi Klubben i lang tid efter min uddannelse var færdig. Efter Datamatikeren arbejdede jeg stadig hver weekend i butikken, samtidig med et fuldtidsjob som softwareudvikler. Over årene skar jeg ned på tid, og i 2021 stoppede jeg efter 10 år i Hi-Fi Klubben da min anden datter kom til verdenen.

  - title: Uddannelse
    layout: list
    content:
      - layout: left
        title: Københavns Erhvervs Akademi (KEA)
        caption: 2011 - 2014
        sub_title: Datamatiker
        description: |
          Uddannelsen bestod primært af programmering i Java og PHP, samt undervisning i de agile udviklings metoder Scrum, Xtreme Programming og Unified Process. Mit eksamens projekt var et custom PHP MVC framework plus en mindre koncept applikation bygget ovenpå.

          Jeg valgte efter skolen ikke at fortsætte på bacheloren, da jeg altid har været meget drevet af learning-by-doing princippet. Jeg ville hellere ud og have fingrene i maskinen på nogle konkrete udviklingsprojekter.

          Nogle af mine skoleprojekter fra dengang, kan findes på min [GitHub](https://github.com/Baune8D) profil.
      - layout: left
        title: Københavns VUC
        caption: 2011 - 2011
        sub_title: Matematik C / B og Engelsk C / B
        description: |
          Da jeg ikke har en gymnasiel uddannelse, havde jeg brug for nogle enkeltfag for at komme ind på Datamatiker uddannelsen. Jeg tog matematik på C og B niveau som turbo hold der hver varede 8 uger. Engelsk C tog jeg først som fjernstudie og senere på B niveau samtidig med matematik holdene.

  - title: Mere om mig
    layout: text
    content: |
      Jeg bor på Frederiksberg med min kone, 2 døtre og vores lille hund.
      
      Udover tid med familien, går det meste af min fritid også med at rode med IT eller elektronik i forskellige afskygninger. Jeg har et homelab derhjmme som kører en masse services som vi bruger i vores hjem og dagligdag, og jeg bruger meget tid på at optimere på vores hjemmenetværk. Jeg nyder at bygge computere og er stadig en gamer i hjertet, så der går da også en del tid med at game med vennerne når tiden tillader det. Jeg elsker også at spille brætspil og har en 3D printer som jeg bl.a. bruger til at printe nye dele til vores favorit spil.
      

# Footer
footer_show_references: true
references_title: Referencer på anmodning

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
]

locale: da_DK
